apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: ns-must-have-secured-label
spec:
  match:
    kinds:
      - apiGroups: 
        - ""
        kinds: 
        - Namespace
  parameters:
    labels: 
      - key: secured
    message: All namespaces must have a "secured" label