apiVersion: configmanagement.gke.io/v1
kind: Repo
metadata:
  name: repo
spec:
  version: 1.0.0
---
apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  # If you are using a Config Sync version 1.11.0 or later, you can use any valid name.
  name: root-sync
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/ZzubbuzZ/test-acm.git
    branch: main
    dir: hello-namespace
    auth: none