apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-test-app
  labels:
    app: my-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-test-app
  template:
    metadata:
      labels:
        app: my-test-app
    spec:
      containers:
      - name: hello-container
        image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: DATABASE_NAME
          value: "postgres"
        - name: DATABASE_USER
          value: "postgres"
        - name: DATABASE_HOST
          value: "python-guestbook-db"
        - name: DATABASE_PORT
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: my-test-service
spec:
  selector:
    app: my-test-app
  ports:
  - port: 80
  type: ClusterIP
